application: brieandsteve-storytime
version: 1
runtime: go
api_version: go1

handlers:
  - url: /static/(.*)
    static_files: src/github.com/shicks/storytime/\1
    upload: src/github.com/shicks/storytime/(.*\.(css|js))
  - url: /.*
    script: _go_app
